# Java Gradle CircleCI configuration file
#
# Check https://circleci.com/docs/2.0/language-java/ for more details
#
# Using 2.1 for Pipelines and codecov Orb
version: 2.1

orbs:
  codecov: codecov/codecov@1.0.4
workflows:
  build:
    jobs:
      - build:
          context:
            - docker-hub-cred
jobs:
  build:
    docker:
      # specify the version you desire here
      - image: cimg/openjdk:8.0
        auth:
          username: $DOCKERHUB_USERNAME
          password: $DOCKERHUB_PASSWORD

      # Specify service dependencies here if necessary
      # CircleCI maintains a library of pre-built images
      # documented at https://circleci.com/docs/2.0/circleci-images/
      # - image: circleci/postgres:9.4

    working_directory: ~/repo

    environment:
      # Customize the JVM maximum heap limit
      JVM_OPTS: -Xmx3200m
      TERM: dumb

    steps:
      - checkout

      # Download and cache dependencies
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "build.gradle" }}
            # fallback to using the latest cache if no exact match is found
            - v1-dependencies-

      - run: ./gradlew dependencies

      - save_cache:
          paths:
            - ~/.gradle
          key: v1-dependencies-{{ checksum "build.gradle" }}

      #split compilation and tests in UI by executing `testClasses` first
      - run: ./gradlew testClasses

      # now run tests!
      - run: ./gradlew check

      - store_test_results:
          path: build/test-results

      # a token must be configured in the CODECOV_TOKEN env variable
      - codecov/upload:
          file: build/reports/jacoco/test/jacocoTestReport.xml