name: CI
on:
  pull_request: {}
permissions: read-all
jobs:
  checks:
    name: checks
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@44c2b7a8a4ea60a981eaca3cf939b5f4305c123b
      with:
        fetch-depth: 0 # for spotless
    - uses: actions/setup-java@99b8673ff64fbf99d8d325f52d9a5bdedb8483e9
      with:
        distribution: 'temurin'
        java-version: 8
    - uses: gradle/gradle-build-action@4c39dd82cd5e1ec7c6fa0173bb41b4b6bb3b86ff
      name: license header check
      with:
        arguments: spotlessCheck -PspotlessFrom=origin/${{ github.base_ref }}
    - uses: gradle/gradle-build-action@4c39dd82cd5e1ec7c6fa0173bb41b4b6bb3b86ff
      name: gradle
      with:
        arguments: check javadoc