name: CI
on:
  pull_request: {}
permissions: read-all
jobs:
  checks:
    name: checks
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@1d96c772d19495a3b5c517cd2bc0cb401ea0529f
      with:
        fetch-depth: 0 # for spotless
    - uses: actions/setup-java@99b8673ff64fbf99d8d325f52d9a5bdedb8483e9
      with:
        distribution: 'temurin'
        java-version: 8
    - uses: gradle/gradle-build-action@fe59895742b4f984530980e4f693943577526b61
      name: license header check
      with:
        arguments: spotlessCheck -PspotlessFrom=origin/${{ github.base_ref }}
    - uses: gradle/gradle-build-action@fe59895742b4f984530980e4f693943577526b61
      name: gradle
      with:
        arguments: check javadoc